export const IS_SLIDEWINDOW_SHOW = "IS_SLIDEWINDOW_SHOW"
export const SLIDEWINDOW_TOGGLE = "SLIDEWINDOW_TOGGLE"
export const SHOW_FEATURE_INFO = "SHOW_FEATURE_INFO"
export const USER_ID_UPDATA = "USER_ID_UPDATA"